language: node_js
node_js:
- '6.10'
deploy:
  provider: lambda
  function_name: bookcrossing
  region: us-east-1
  role: arn:aws:iam::130143276000:role/service-role/bookCrossing
  runtime: nodejs6.10
  handler_name: index.handler
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: B9ssWMepoyPsoIWKmzWiNSctJZw4aAkIWY7Awc4s6oyqkGa02A2zuukEcxkqvs/7i5MMUAoBCoiTrM05KaqAdt0XuKZBLhZezP1nsBonwYVFxsVCGFt/WWZWUWcoBSWAUUN3dWUuoTrscyiqVZaNoQjstoxnbEkAY8gwok9BAIZWxcX4cb/fPr6MIFtW9zyEDiwm2NWqV3D0raHuPfgzkQ1G6TcTAEVmBXi0Qzro2d6F7u6XsMG2kCXowg/B07Ht6hWzcbrf5zU18XfA0zeTCcmLs2nbWfeuKoAoGQUCHx+TJMrLZVNz1Bm0++K81TWb87yl0gHcFrMlz7LOhzvXDpJMmPdLUECpASn2T6sEi6atFKs6CB5RmubWR/a5l222g8c7rmEYLukYRUnAiOKpc9Bk1FgXNWRY9dbHS+f5MCpRoJU58ihYvS+UkbZOoefyNmqXcV+SjxqDFOQVkzaivQH4y29STSbE6E4wTbhyx3kvHOK5Qstf4/Wiz1Cp4OCjKy4/Dh+R2uyaYiR2ark4yb7AyOANOmZ9HcTwMdRSyh8dhRme+ySpmBwHYMrmQDSx9jUlf6ggh4XH8844wh5xV+fPpS8l23l4uRKT9NTA3oSnWMYo2lwAiuTwpRJCPQvL9XipCGZH9xUvyg3xnqNu473lJOQujQgDuC6Uxkw8p7M=
